INSERT INTO myshop_schema.Country (id, name) VALUES (0, 'Россия');
INSERT INTO myshop_schema.Country (id, name) VALUES (1, 'Украина');
INSERT INTO myshop_schema.Country (id, name) VALUES (2, 'Абхазия');
INSERT INTO myshop_schema.Country (id, name) VALUES (3, 'Австралия');
INSERT INTO myshop_schema.Country (id, name) VALUES (4, 'Австрия');
INSERT INTO myshop_schema.Country (id, name) VALUES (5, 'Азербайджан');
INSERT INTO myshop_schema.Country (id, name) VALUES (6, 'Албания');
INSERT INTO myshop_schema.Country (id, name) VALUES (7, 'Алжир');
INSERT INTO myshop_schema.Country (id, name) VALUES (8, 'Ангола');
INSERT INTO myshop_schema.Country (id, name) VALUES (9, 'Ангуилья');
INSERT INTO myshop_schema.Country (id, name) VALUES (10, 'Андорра');
INSERT INTO myshop_schema.Country (id, name) VALUES (11, 'Антигуа и Барбуда');
INSERT INTO myshop_schema.Country (id, name) VALUES (12, 'Антильские о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (13, 'Аргентина');
INSERT INTO myshop_schema.Country (id, name) VALUES (14, 'Армения');
INSERT INTO myshop_schema.Country (id, name) VALUES (15, 'Арулько');
INSERT INTO myshop_schema.Country (id, name) VALUES (16, 'Афганистан');
INSERT INTO myshop_schema.Country (id, name) VALUES (17, 'Багамские о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (18, 'Бангладеш');
INSERT INTO myshop_schema.Country (id, name) VALUES (19, 'Барбадос');
INSERT INTO myshop_schema.Country (id, name) VALUES (20, 'Бахрейн');
INSERT INTO myshop_schema.Country (id, name) VALUES (21, 'Беларусь');
INSERT INTO myshop_schema.Country (id, name) VALUES (22, 'Белиз');
INSERT INTO myshop_schema.Country (id, name) VALUES (23, 'Бельгия');
INSERT INTO myshop_schema.Country (id, name) VALUES (24, 'Бенин');
INSERT INTO myshop_schema.Country (id, name) VALUES (25, 'Бермуды');
INSERT INTO myshop_schema.Country (id, name) VALUES (26, 'Болгария');
INSERT INTO myshop_schema.Country (id, name) VALUES (27, 'Боливия');
INSERT INTO myshop_schema.Country (id, name) VALUES (28, 'Босния/Герцеговина');
INSERT INTO myshop_schema.Country (id, name) VALUES (29, 'Ботсвана');
INSERT INTO myshop_schema.Country (id, name) VALUES (30, 'Бразилия');
INSERT INTO myshop_schema.Country (id, name) VALUES (31, 'Британские Виргинские о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (32, 'Бруней');
INSERT INTO myshop_schema.Country (id, name) VALUES (33, 'Буркина Фасо');
INSERT INTO myshop_schema.Country (id, name) VALUES (34, 'Бурунди');
INSERT INTO myshop_schema.Country (id, name) VALUES (35, 'Бутан');
INSERT INTO myshop_schema.Country (id, name) VALUES (36, 'Валлис и Футуна о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (37, 'Вануату');
INSERT INTO myshop_schema.Country (id, name) VALUES (38, 'Великобритания');
INSERT INTO myshop_schema.Country (id, name) VALUES (39, 'Венгрия');
INSERT INTO myshop_schema.Country (id, name) VALUES (40, 'Венесуэла');
INSERT INTO myshop_schema.Country (id, name) VALUES (41, 'Восточный Тимор');
INSERT INTO myshop_schema.Country (id, name) VALUES (42, 'Вьетнам');
INSERT INTO myshop_schema.Country (id, name) VALUES (43, 'Габон');
INSERT INTO myshop_schema.Country (id, name) VALUES (44, 'Гаити');
INSERT INTO myshop_schema.Country (id, name) VALUES (45, 'Гайана');
INSERT INTO myshop_schema.Country (id, name) VALUES (46, 'Гамбия');
INSERT INTO myshop_schema.Country (id, name) VALUES (47, 'Гана');
INSERT INTO myshop_schema.Country (id, name) VALUES (48, 'Гваделупа');
INSERT INTO myshop_schema.Country (id, name) VALUES (49, 'Гватемала');
INSERT INTO myshop_schema.Country (id, name) VALUES (50, 'Гвинея');
INSERT INTO myshop_schema.Country (id, name) VALUES (51, 'Гвинея-Бисау');
INSERT INTO myshop_schema.Country (id, name) VALUES (52, 'Германия');
INSERT INTO myshop_schema.Country (id, name) VALUES (53, 'Гернси о-в');
INSERT INTO myshop_schema.Country (id, name) VALUES (54, 'Гибралтар');
INSERT INTO myshop_schema.Country (id, name) VALUES (55, 'Гондурас');
INSERT INTO myshop_schema.Country (id, name) VALUES (56, 'Гонконг');
INSERT INTO myshop_schema.Country (id, name) VALUES (57, 'Гренада');
INSERT INTO myshop_schema.Country (id, name) VALUES (58, 'Гренландия');
INSERT INTO myshop_schema.Country (id, name) VALUES (59, 'Греция');
INSERT INTO myshop_schema.Country (id, name) VALUES (60, 'Грузия');
INSERT INTO myshop_schema.Country (id, name) VALUES (61, 'Дания');
INSERT INTO myshop_schema.Country (id, name) VALUES (62, 'Джерси о-в');
INSERT INTO myshop_schema.Country (id, name) VALUES (63, 'Джибути');
INSERT INTO myshop_schema.Country (id, name) VALUES (64, 'Доминиканская республика');
INSERT INTO myshop_schema.Country (id, name) VALUES (65, 'Египет');
INSERT INTO myshop_schema.Country (id, name) VALUES (66, 'Замбия');
INSERT INTO myshop_schema.Country (id, name) VALUES (67, 'Западная Сахара');
INSERT INTO myshop_schema.Country (id, name) VALUES (68, 'Зимбабве');
INSERT INTO myshop_schema.Country (id, name) VALUES (69, 'Израиль');
INSERT INTO myshop_schema.Country (id, name) VALUES (70, 'Индия');
INSERT INTO myshop_schema.Country (id, name) VALUES (71, 'Индонезия');
INSERT INTO myshop_schema.Country (id, name) VALUES (72, 'Иордания');
INSERT INTO myshop_schema.Country (id, name) VALUES (73, 'Ирак');
INSERT INTO myshop_schema.Country (id, name) VALUES (74, 'Иран');
INSERT INTO myshop_schema.Country (id, name) VALUES (75, 'Ирландия');
INSERT INTO myshop_schema.Country (id, name) VALUES (76, 'Исландия');
INSERT INTO myshop_schema.Country (id, name) VALUES (77, 'Испания');
INSERT INTO myshop_schema.Country (id, name) VALUES (78, 'Италия');
INSERT INTO myshop_schema.Country (id, name) VALUES (79, 'Йемен');
INSERT INTO myshop_schema.Country (id, name) VALUES (80, 'Кабо-Верде');
INSERT INTO myshop_schema.Country (id, name) VALUES (81, 'Казахстан');
INSERT INTO myshop_schema.Country (id, name) VALUES (82, 'Камбоджа');
INSERT INTO myshop_schema.Country (id, name) VALUES (83, 'Камерун');
INSERT INTO myshop_schema.Country (id, name) VALUES (84, 'Канада');
INSERT INTO myshop_schema.Country (id, name) VALUES (85, 'Катар');
INSERT INTO myshop_schema.Country (id, name) VALUES (86, 'Кения');
INSERT INTO myshop_schema.Country (id, name) VALUES (87, 'Кипр');
INSERT INTO myshop_schema.Country (id, name) VALUES (88, 'Кирибати');
INSERT INTO myshop_schema.Country (id, name) VALUES (89, 'Китай');
INSERT INTO myshop_schema.Country (id, name) VALUES (90, 'Колумбия');
INSERT INTO myshop_schema.Country (id, name) VALUES (91, 'Коморские о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (92, 'Конго (Brazzaville)');
INSERT INTO myshop_schema.Country (id, name) VALUES (93, 'Конго (Kinshasa)');
INSERT INTO myshop_schema.Country (id, name) VALUES (94, 'Коста-Рика');
INSERT INTO myshop_schema.Country (id, name) VALUES (95, 'Кот-д''''Ивуар');
INSERT INTO myshop_schema.Country (id, name) VALUES (96, 'Куба');
INSERT INTO myshop_schema.Country (id, name) VALUES (97, 'Кувейт');
INSERT INTO myshop_schema.Country (id, name) VALUES (98, 'Кука о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (99, 'Кыргызстан');
INSERT INTO myshop_schema.Country (id, name) VALUES (100, 'Лаос');
INSERT INTO myshop_schema.Country (id, name) VALUES (101, 'Латвия');
INSERT INTO myshop_schema.Country (id, name) VALUES (102, 'Лесото');
INSERT INTO myshop_schema.Country (id, name) VALUES (103, 'Либерия');
INSERT INTO myshop_schema.Country (id, name) VALUES (104, 'Ливан');
INSERT INTO myshop_schema.Country (id, name) VALUES (105, 'Ливия');
INSERT INTO myshop_schema.Country (id, name) VALUES (106, 'Литва');
INSERT INTO myshop_schema.Country (id, name) VALUES (107, 'Лихтенштейн');
INSERT INTO myshop_schema.Country (id, name) VALUES (108, 'Люксембург');
INSERT INTO myshop_schema.Country (id, name) VALUES (109, 'Маврикий');
INSERT INTO myshop_schema.Country (id, name) VALUES (110, 'Мавритания');
INSERT INTO myshop_schema.Country (id, name) VALUES (111, 'Мадагаскар');
INSERT INTO myshop_schema.Country (id, name) VALUES (112, 'Македония');
INSERT INTO myshop_schema.Country (id, name) VALUES (113, 'Малави');
INSERT INTO myshop_schema.Country (id, name) VALUES (114, 'Малайзия');
INSERT INTO myshop_schema.Country (id, name) VALUES (115, 'Мали');
INSERT INTO myshop_schema.Country (id, name) VALUES (116, 'Мальдивские о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (117, 'Мальта');
INSERT INTO myshop_schema.Country (id, name) VALUES (118, 'Мартиника о-в');
INSERT INTO myshop_schema.Country (id, name) VALUES (119, 'Мексика');
INSERT INTO myshop_schema.Country (id, name) VALUES (120, 'Мозамбик');
INSERT INTO myshop_schema.Country (id, name) VALUES (121, 'Молдова');
INSERT INTO myshop_schema.Country (id, name) VALUES (122, 'Монако');
INSERT INTO myshop_schema.Country (id, name) VALUES (123, 'Монголия');
INSERT INTO myshop_schema.Country (id, name) VALUES (124, 'Марокко');
INSERT INTO myshop_schema.Country (id, name) VALUES (125, 'Мьянма (Бирма)');
INSERT INTO myshop_schema.Country (id, name) VALUES (126, 'Мэн о-в');
INSERT INTO myshop_schema.Country (id, name) VALUES (127, 'Намибия');
INSERT INTO myshop_schema.Country (id, name) VALUES (128, 'Науру');
INSERT INTO myshop_schema.Country (id, name) VALUES (129, 'Непал');
INSERT INTO myshop_schema.Country (id, name) VALUES (130, 'Нигер');
INSERT INTO myshop_schema.Country (id, name) VALUES (131, 'Нигерия');
INSERT INTO myshop_schema.Country (id, name) VALUES (132, 'Нидерланды (Голландия)');
INSERT INTO myshop_schema.Country (id, name) VALUES (133, 'Никарагуа');
INSERT INTO myshop_schema.Country (id, name) VALUES (134, 'Новая Зеландия');
INSERT INTO myshop_schema.Country (id, name) VALUES (135, 'Новая Каледония о-в');
INSERT INTO myshop_schema.Country (id, name) VALUES (136, 'Норвегия');
INSERT INTO myshop_schema.Country (id, name) VALUES (137, 'Норфолк о-в');
INSERT INTO myshop_schema.Country (id, name) VALUES (138, 'О.А.Э.');
INSERT INTO myshop_schema.Country (id, name) VALUES (139, 'Оман');
INSERT INTO myshop_schema.Country (id, name) VALUES (140, 'Пакистан');
INSERT INTO myshop_schema.Country (id, name) VALUES (141, 'Панама');
INSERT INTO myshop_schema.Country (id, name) VALUES (142, 'Папуа Новая Гвинея');
INSERT INTO myshop_schema.Country (id, name) VALUES (143, 'Парагвай');
INSERT INTO myshop_schema.Country (id, name) VALUES (144, 'Перу');
INSERT INTO myshop_schema.Country (id, name) VALUES (145, 'Питкэрн о-в');
INSERT INTO myshop_schema.Country (id, name) VALUES (146, 'Польша');
INSERT INTO myshop_schema.Country (id, name) VALUES (147, 'Португалия');
INSERT INTO myshop_schema.Country (id, name) VALUES (148, 'Пуэрто Рико');
INSERT INTO myshop_schema.Country (id, name) VALUES (149, 'Реюньон');
INSERT INTO myshop_schema.Country (id, name) VALUES (150, 'Руанда');
INSERT INTO myshop_schema.Country (id, name) VALUES (151, 'Румыния');
INSERT INTO myshop_schema.Country (id, name) VALUES (152, 'США');
INSERT INTO myshop_schema.Country (id, name) VALUES (153, 'Сальвадор');
INSERT INTO myshop_schema.Country (id, name) VALUES (154, 'Самоа');
INSERT INTO myshop_schema.Country (id, name) VALUES (155, 'Сан-Марино');
INSERT INTO myshop_schema.Country (id, name) VALUES (156, 'Сан-Томе и Принсипи');
INSERT INTO myshop_schema.Country (id, name) VALUES (157, 'Саудовская Аравия');
INSERT INTO myshop_schema.Country (id, name) VALUES (158, 'Свазиленд');
INSERT INTO myshop_schema.Country (id, name) VALUES (159, 'Святая Люсия');
INSERT INTO myshop_schema.Country (id, name) VALUES (160, 'Святой Елены о-в');
INSERT INTO myshop_schema.Country (id, name) VALUES (161, 'Северная Корея');
INSERT INTO myshop_schema.Country (id, name) VALUES (162, 'Сейшеллы');
INSERT INTO myshop_schema.Country (id, name) VALUES (163, 'Сен-Пьер и Микелон');
INSERT INTO myshop_schema.Country (id, name) VALUES (164, 'Сенегал');
INSERT INTO myshop_schema.Country (id, name) VALUES (165, 'Сент Китс и Невис');
INSERT INTO myshop_schema.Country (id, name) VALUES (166, 'Сент-Винсент и Гренадины');
INSERT INTO myshop_schema.Country (id, name) VALUES (167, 'Сербия');
INSERT INTO myshop_schema.Country (id, name) VALUES (168, 'Сингапур');
INSERT INTO myshop_schema.Country (id, name) VALUES (169, 'Сирия');
INSERT INTO myshop_schema.Country (id, name) VALUES (170, 'Словакия');
INSERT INTO myshop_schema.Country (id, name) VALUES (171, 'Словения');
INSERT INTO myshop_schema.Country (id, name) VALUES (172, 'Соломоновы о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (173, 'Сомали');
INSERT INTO myshop_schema.Country (id, name) VALUES (174, 'Судан');
INSERT INTO myshop_schema.Country (id, name) VALUES (175, 'Суринам');
INSERT INTO myshop_schema.Country (id, name) VALUES (176, 'Сьерра-Леоне');
INSERT INTO myshop_schema.Country (id, name) VALUES (177, 'Таджикистан');
INSERT INTO myshop_schema.Country (id, name) VALUES (178, 'Тайвань');
INSERT INTO myshop_schema.Country (id, name) VALUES (179, 'Таиланд');
INSERT INTO myshop_schema.Country (id, name) VALUES (180, 'Танзания');
INSERT INTO myshop_schema.Country (id, name) VALUES (181, 'Того');
INSERT INTO myshop_schema.Country (id, name) VALUES (182, 'Токелау о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (183, 'Тонга');
INSERT INTO myshop_schema.Country (id, name) VALUES (184, 'Тринидад и Тобаго');
INSERT INTO myshop_schema.Country (id, name) VALUES (185, 'Тувалу');
INSERT INTO myshop_schema.Country (id, name) VALUES (186, 'Тунис');
INSERT INTO myshop_schema.Country (id, name) VALUES (187, 'Туркменистан');
INSERT INTO myshop_schema.Country (id, name) VALUES (188, 'Туркс и Кейкос');
INSERT INTO myshop_schema.Country (id, name) VALUES (189, 'Турция');
INSERT INTO myshop_schema.Country (id, name) VALUES (190, 'Уганда');
INSERT INTO myshop_schema.Country (id, name) VALUES (191, 'Узбекистан');
INSERT INTO myshop_schema.Country (id, name) VALUES (192, 'Уругвай');
INSERT INTO myshop_schema.Country (id, name) VALUES (193, 'Фарерские о-ва');
INSERT INTO myshop_schema.Country (id, name) VALUES (194, 'Фиджи');
INSERT INTO myshop_schema.Country (id, name) VALUES (195, 'Филиппины');
INSERT INTO myshop_schema.Country (id, name) VALUES (196, 'Финляндия');
INSERT INTO myshop_schema.Country (id, name) VALUES (197, 'Франция');
INSERT INTO myshop_schema.Country (id, name) VALUES (198, 'Французская Гвинея');
INSERT INTO myshop_schema.Country (id, name) VALUES (199, 'Французская Полинезия');
INSERT INTO myshop_schema.Country (id, name) VALUES (200, 'Хорватия');
INSERT INTO myshop_schema.Country (id, name) VALUES (201, 'Чад');
INSERT INTO myshop_schema.Country (id, name) VALUES (202, 'Черногория');
INSERT INTO myshop_schema.Country (id, name) VALUES (203, 'Чехия');
INSERT INTO myshop_schema.Country (id, name) VALUES (204, 'Чили');
INSERT INTO myshop_schema.Country (id, name) VALUES (205, 'Швейцария');
INSERT INTO myshop_schema.Country (id, name) VALUES (206, 'Швеция');
INSERT INTO myshop_schema.Country (id, name) VALUES (207, 'Шри-Ланка');
INSERT INTO myshop_schema.Country (id, name) VALUES (208, 'Эквадор');
INSERT INTO myshop_schema.Country (id, name) VALUES (209, 'Экваториальная Гвинея');
INSERT INTO myshop_schema.Country (id, name) VALUES (210, 'Эритрея');
INSERT INTO myshop_schema.Country (id, name) VALUES (211, 'Эстония');
INSERT INTO myshop_schema.Country (id, name) VALUES (212, 'Эфиопия');
INSERT INTO myshop_schema.Country (id, name) VALUES (213, 'ЮАР');
INSERT INTO myshop_schema.Country (id, name) VALUES (214, 'Южная Корея');
INSERT INTO myshop_schema.Country (id, name) VALUES (215, 'Южная Осетия');
INSERT INTO myshop_schema.Country (id, name) VALUES (216, 'Ямайка');
INSERT INTO myshop_schema.Country (id, name) VALUES (217, 'Япония');