INSERT INTO MYSHOP_SCHEMA.DELIVERY_STATUS (NAME) VALUES ('Await');
INSERT INTO MYSHOP_SCHEMA.DELIVERY_STATUS (NAME) VALUES ('Given to courier');
INSERT INTO MYSHOP_SCHEMA.DELIVERY_STATUS (NAME) VALUES ('In progress');
INSERT INTO MYSHOP_SCHEMA.DELIVERY_STATUS (NAME) VALUES ('Sent');