INSERT INTO MYSHOP_SCHEMA.PROPERTY_GROUP (NAME, SOLO, VISIBLE) VALUES ('Camera', 1, 1);
INSERT INTO MYSHOP_SCHEMA.PROPERTY_GROUP (NAME, SOLO, VISIBLE) VALUES ('Brand', 1, 1);
INSERT INTO MYSHOP_SCHEMA.PROPERTY_GROUP (NAME, SOLO, VISIBLE) VALUES ('Features', 0, 1);