INSERT INTO MYSHOP_SCHEMA.CATEGORY (NAME, VISIBLE) VALUES ('No category', 1);
INSERT INTO MYSHOP_SCHEMA.CATEGORY (NAME, VISIBLE) VALUES ('Non-professional', 1);
INSERT INTO MYSHOP_SCHEMA.CATEGORY (NAME, VISIBLE) VALUES ('Professional', 1);