INSERT INTO MYSHOP_SCHEMA.ROLE (ROLE_ID, NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO MYSHOP_SCHEMA.ROLE (ROLE_ID, NAME) VALUES (4, 'ROLE_ANONYM');
INSERT INTO MYSHOP_SCHEMA.ROLE (ROLE_ID, NAME) VALUES (3, 'ROLE_CLIENT');
INSERT INTO MYSHOP_SCHEMA.ROLE (ROLE_ID, NAME) VALUES (2, 'ROLE_MANAGER');